# Site settings
author: Cameron Kingsley
title: Cameron Kingsley's Coding Adventures
header-img: img/gears-bg.png
email: cameron.kingsley13@gmail.com
copyright_name: Cameron Kingsley
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Completed Work
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kingsley113

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
